DB課題3
miki123k/quelcode-db pull request #4
Opened 2020-07-26 15:53 UTC by miki123k

## DB課題3 001~005
## やったこと
- SQL文の作成、構文チェッカーにかけています
- SQL文の実行
- 結果の画面キャプチャを各フォルダ格納

2020-07-27 02:33 UTC, piasoratech requested changes
sql文は最後`;`を付けて終わるようにしてください。
それ以外の部分はOKです

2020-07-27 02:38 UTC, miki123k commented
## やったこと
- 全てのファイルのsql文末に;を付けました

2020-07-27 02:42 UTC, piasoratech reviewed
No001～005まで確認しました
OKです！

2020-07-29 01:45 UTC, miki123k commented
## DB課題3 006〜010
## やったこと
- SQL文の作成、構文チェッカーにかけています
- SQL文の実行
- 結果の画面キャプチャを各フォルダ格納

2020-07-30 02:44 UTC, Yuzunoha commented
008 削除されているチャットルームが出てしまっているようなので確認をお願いします！

2020-07-30 02:55 UTC, miki123k commented
- 008 削除されているチャットルームが出ないよう修正、実行後の画面キャプチャの変更をいたしました

2020-07-30 05:50 UTC, piasoratech reviewed
No006～No010まで確認しました！
OKです！

2020-07-30 07:51 UTC, miki123k commented
## DB課題3 011〜014
## やったこと
- SQL文の作成
- SQL文の実行
- 結果の画面キャプチャを各フォルダ格納

2020-07-31 01:14 UTC, piasoratech approved these changes
OKです！
お疲れ様でした！

2020-07-31 01:15 UTC, merged